import { DashboardLayout } from '@/components/DashboardLayout/DashboardLayout';
import type { Metadata } from 'next';
import { Cairo } from 'next/font/google';
import './globals.css';

const cairo = Cairo({
  variable: '--font-cairo',
  subsets: ['arabic', 'latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ar' dir='rtl'>
      <body className={`${cairo.variable} font-cairo antialiased arabic-text`}>
        <DashboardLayout>{children}</DashboardLayout>
      </body>
    </html>
  );
}
